# Generated by Django 2.2 on 2020-02-24 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient_reg', '0002_auto_20200223_1725'),
        ('login_reg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(max_length=100)),
                ('date_of_service', models.DateField()),
                ('issue', models.TextField()),
                ('follow_up', models.BooleanField()),
                ('follow_up_days', models.IntegerField()),
                ('finished', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_claim', to='patient_reg.Patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_claim', to='login_reg.User')),
            ],
        ),
    ]
