# Generated by Django 2.2 on 2020-02-24 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_claim_follow_up_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='follow_up',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='follow_up_date',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='follow_up_days',
        ),
    ]
