# Generated by Django 2.2 on 2020-02-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20200224_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='insurance',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
