# Generated by Django 2.2 on 2020-02-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='follow_up_date',
            field=models.DateField(auto_now=True),
        ),
    ]
