# Generated by Django 2.2 on 2020-02-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_action_follow_up_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='follow_up_days',
        ),
        migrations.AlterField(
            model_name='action',
            name='follow_up_date',
            field=models.DateField(),
        ),
    ]
