# Generated by Django 2.2 on 2020-02-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20200227_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='claim',
        ),
        migrations.AddField(
            model_name='claim',
            name='actions',
            field=models.ManyToManyField(related_name='claim_action', to='cms.Action'),
        ),
    ]
