# Generated by Django 2.2 on 2020-02-28 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='standard', max_length=15),
            preserve_default=False,
        ),
    ]
